baseURL = "https://desmo13.github.io/ministerio-de-la-verdad/"
canonifyURLs = true
relativeURLs = true
pluralizeListTitles = false
summaryLength = 25

theme = "BlogRa"
languageCode = "es-es"
title = "El Ministerio de la Verdad"

disqusShortname = ""

[params]
    description = "El blog definitivo para la discusión y promoción de ideas progresistas y revolucionarias."
    contactEmail = "tu-email@dominio.com"
    footer = "© 2024 El Ministerio de la Verdad. Todos los derechos reservados."
    googleSearch = "google-cse-key"
    googleAnalytics = "G-A1B2C3D4E5"
    adsense = "adsense-key"
    math = false
    mermaid = false

    # Social Media Params
    facebook = "https://www.facebook.com/DevHacker-2351204168278028"
    twitter = "https://twitter.com/tucuenta"
    youtube = "https://www.youtube.com/channel/UC6uDg4IlPbLh2xNKrqnBczw"
    instagram = "https://www.instagram.com/tucuenta"
    github = "https://github.com/desmo13"
    pinterest = ""
    linkedin = "https://www.linkedin.com/in/rafed-m-yasir/"

# Configure the site menu here
[menu]
    [[menu.main]]
        name = "Inicio"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "blog"
        name = "Publicaciones"
        url = "/posts/"
        weight = 2

    [[menu.main]]
        name = "Acerca de"
        url = "/about/"
        weight = 3
    [[menu.main]]
        name = "Contacto"
        url = "/contact/"
        weight = 4

# No tocar esta sección
[markup.goldmark.renderer]
    unsafe = true
